# Generated by Django 5.2.4 on 2025-07-14 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0002_search'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
