# Generated by Django 5.2.4 on 2025-07-23 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0005_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
